version: '3'

services:
  db-dialog:
    image: postgres:15.1
    container_name: db-dialog
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=master
    volumes:
      - ./db/master/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - service-dialog-network
    ports:
      - "5435:5432"
#  master:
#    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
#    image: "citusdata/citus:12.1.2"
#    labels: ["com.citusdata.role=Master"]
#    environment: &AUTH
#      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
#      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
#      PGUSER: "${POSTGRES_USER:-postgres}"
#      PGPASSWORD: "${POSTGRES_PASSWORD}"
#      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
##    volumes:
##      - ./db/master/init.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - "5432:5432"
#    networks:
#      - service-dialog-network
#  worker:
#    image: "citusdata/citus:12.1.2"
#    labels: ["com.citusdata.role=Worker"]
#    depends_on: [manager]
#    environment: *AUTH
#    command: "/wait-for-manager.sh"
#    volumes:
#      - healthcheck-volume:/healthcheck
#    networks:
#      - service-dialog-network
#  manager:
#    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
#    image: "citusdata/membership-manager:0.3.0"
#    volumes:
#      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
#      - healthcheck-volume:/healthcheck
#    depends_on: [master]
#    environment: *AUTH
#    networks:
#      - service-dialog-network
volumes:
  healthcheck-volume:
networks:
  service-dialog-network: